spring:
  application:
    name: system
  datasource:
    url: "jdbc:mysql://localhost:3306/courseimooc?CharacterEncoding=UTF8&AutoReconnect=True&serverTimezone=GMT-8"
    username: courseiMooc
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: "classpath:/mapper/*.xml"

logging:
  level:
    com.course.server.mapper: trace
