spring:
  application:
    name: system
  datasource:
    url: "jdbc:mysql://localhost:3306/courseimooc?CharacterEncoding=UTF8&AutoReconnect=True"
    username: courseiMooc
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9001
  servlet:
    context-path: "/system"

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka/"
